### ISSUE TITLE
mtls认证是不是需要额外patch

### ISSUE THREAD

**Issue by vinsonzou** [api7/lua-resty-http#11]
环境:
- OpenResty 1.19.9.1

使用mTLS认证总是报如下错误，是不是需要额外patch？我看文档也没提到这个。如有patch，能通用给OpenResty或者原生Nginx么？
```
<html>
<head><title>400 No required SSL certificate was sent</title></head>
<body bgcolor="white">
<center><h1>400 Bad Request</h1></center>
<center>No required SSL certificate was sent</center>
<hr><center>nginx</center>
</body>
</html>
```

**Comment by spacewander** [comment]
Yes. Better not use this library outside APISIX. We don't guarantee its API compatibility or other stuff.

**Comment by vinsonzou** [comment]
I have used Kong's cosocket-mtls patch and slightly modified this lua-resty-http.
